server:
  port: 8888


spring:
  http:
    encoding:
      force: false
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  mvc:
    static-path-pattern: /**


mybatis:
  mapper-locations: classpath:mybatis/dao/*.xml
  type-aliases-package: com.czh.sharding.entity
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true